#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "pgtbltest")
def test_pgtbltest():
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)

@test(10, "pgtbltest: ugetpid", parent=test_pgtbltest)
def test_ugetpid_():
    r.match('^ugetpid_test: OK$')

@test(10, "pgtbltest: print_kpgtbl", parent=test_pgtbltest)
def test_print_kpgtbl_():
    r.match(
        r'^va 0x0+ pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x1000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x2000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x3000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x4000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x5000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x6000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x7000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x8000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0x9000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFF6000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFF7000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFF8000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFF9000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFA000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFB000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFC000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFD000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFE000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
        r'^va 0xFFFFF000 pte 0x[0-9A-Fa-f]+ pa 0x[0-9A-Fa-f]+ perm 0x[0-9A-Fa-f]+$',
    )

@test(15, "pgtbltest: superpg", parent=test_pgtbltest)
def test_superpg_():
    r.match('^superpg_test: OK$')

@test(5, "answers-pgtbl.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-pgtbl.txt")

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)

@test(10, "usertests: all tests", parent=test_usertests)
def test_usertests():
    r.match('^ALL TESTS PASSED$')

@test(1, "time")
def test_time():
    check_time()

run_tests()
